[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.0"
actix-multipart = "0.6.0"
actix-web = {version="4.0.1", features=["openssl"]}
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["chrono", "r2d2", "sqlite"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures-util = "0.3.21"
lazy_static = "1.4.0"
log = "0.4.17"
getset = "0.1.2"
openssl = "0.10.38"
rand = "0.8.4"
regex = "1.6.0"
sanitize-filename = "0.4.0"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.78"
uuid = { version = "1.3.1", features = ["serde", "v1", "v4"] }

[dev-dependencies]
mime = "0.3.16"
serial_test = "2.0.0"
